version: 2.1

orbs:
    maven: circleci/maven@0.0.12
workflows:
    maven_test:
        jobs:
            - maven/test # checkout, build, test, and upload test results
    nightly:
        triggers:
            # Run Nightly at 3 am, only build master
            -   schedule:
                    cron: "10 * * * *"
                    filters:
                        branches:
                            only:
                                - v2.20
        jobs:
            - maven/test