version: 2.1

orbs:
    maven: circleci/maven@1.0.0
workflows:
    maven_test:
        jobs:
            - maven/test # checkout, build, test, and upload test results
    nightly:
        triggers:
            # Run Nightly at 3 am, only build master
            -   schedule:
                    cron: "15 3 * * *"
                    filters:
                        branches:
                            only:
                                - master
        jobs:
            - maven/test